# plugin/tests/integration/test_agent_catalog.py
"""Tests for §Agent Catalog generation in index.md."""
from datetime import date, timedelta
import pytest
from pathlib import Path
from conftest import run_lint, _write_synthesis_page

TODAY = date.today().isoformat()
STALE_DATE = (date.today() - timedelta(days=100)).isoformat()

AUTO_START = "<!-- AUTO-GENERATED by lint.py — do not edit this section -->"
AUTO_END = "<!-- END AUTO-GENERATED -->"


def _entity(type_name, confidence="high", last_updated=None, summary=None, open_qs=0,
            status="active", extra=""):
    lu = last_updated or TODAY
    sq = "".join(f"- [ ] Open question {i}\n" for i in range(open_qs))
    s = f'summary: "{summary}"\n' if summary else ""
    return (
        f"---\ntype: {type_name}\nstatus: {status}\nlast-updated: {lu}\n"
        f"quarter: 2026-Q2\nokr: []\nconfidence: {confidence}\n"
        f"sources: []\nrelated: []\ntags: []\n{s}{extra}---\n# Page\n\n"
        f"## Open questions\n{sq}"
    )


def test_catalog_inserted_into_index_after_lint(wiki):
    """After lint runs, index.md contains the AUTO-GENERATED catalog block."""
    (wiki / "wiki/shopify-competitor.md").write_text(
        _entity("competitor", summary="Shopify: 70+ reports all plans; no Z report; Sidekick AI")
    )
    run_lint(wiki)
    index_content = (wiki / "wiki/index.md").read_text()
    assert AUTO_START in index_content
    assert "## Agent Catalog" in index_content
    assert "[[shopify-competitor]]" in index_content


def test_catalog_check_prefix(wiki):
    """High-confidence, current, no open-Qs entity gets ✓ prefix."""
    (wiki / "wiki/shopify-competitor.md").write_text(
        _entity("competitor", confidence="high",
                summary="Shopify: 70+ reports all plans; no Z report capability confirmed")
    )
    run_lint(wiki)
    index = (wiki / "wiki/index.md").read_text()
    assert "✓ [[shopify-competitor]]" in index


def test_catalog_delta_prefix_stale(wiki):
    """Stale entity (>90 days old, status:active) gets △ prefix."""
    (wiki / "wiki/old-competitor.md").write_text(
        _entity("competitor", last_updated=STALE_DATE,
                summary="Old Competitor: legacy product with limited reporting features confirmed")
    )
    run_lint(wiki)
    index = (wiki / "wiki/index.md").read_text()
    assert "△ [[old-competitor]]" in index


def test_catalog_delta_prefix_open_questions(wiki):
    """Entity with open questions gets △ prefix regardless of confidence."""
    (wiki / "wiki/shopify-competitor.md").write_text(
        _entity("competitor", confidence="high", open_qs=2,
                summary="Shopify: 70+ reports all plans; no Z report; Sidekick AI present now")
    )
    run_lint(wiki)
    index = (wiki / "wiki/index.md").read_text()
    assert "△ [[shopify-competitor]]" in index


def test_catalog_regenerates_on_second_run(wiki):
    """Running lint twice replaces the catalog block, not appends."""
    (wiki / "wiki/shopify-competitor.md").write_text(
        _entity("competitor",
                summary="Shopify: 70+ reports all plans; no Z report; Sidekick AI confirmed")
    )
    run_lint(wiki)
    run_lint(wiki)
    index = (wiki / "wiki/index.md").read_text()
    assert index.count(AUTO_START) == 1, "Catalog block must appear exactly once"


def test_catalog_preserves_obsidian_section(wiki):
    """Human-authored content in index.md after the AUTO-GENERATED block is preserved."""
    index_path = wiki / "wiki/index.md"
    existing = index_path.read_text()
    index_path.write_text(existing + "\n## Obsidian Navigation\n\nSome Dataview query here.\n")
    run_lint(wiki)
    new_content = index_path.read_text()
    assert "Obsidian Navigation" in new_content
    assert "Dataview query here" in new_content


def test_synthesis_pages_not_in_catalog(wiki):
    """Synthesis-type pages (index, overview, _health) do not appear in catalog entity sections."""
    run_lint(wiki)
    index = (wiki / "wiki/index.md").read_text()
    start = index.find(AUTO_START)
    end = index.find(AUTO_END)
    if start >= 0 and end >= 0:
        block = index[start:end]
        catalog_start = block.find("## Agent Catalog")
        if catalog_start >= 0:
            block = block[catalog_start:]
        assert "[[overview]]" not in block
        assert "[[_health]]" not in block


# ── Task 5: digests/catalog.md ────────────────────────────────────────────────

def test_digests_catalog_created(wiki):
    """lint.py creates wiki/digests/catalog.md listing all digests."""
    digest_path = wiki / "wiki/digests/research-shopify-2026-05-07.md"
    digest_path.write_text(
        "---\n"
        "type: source\n"
        "status: active\n"
        f"last-updated: {TODAY}\n"
        "quarter: 2026-Q2\n"
        "okr: []\n"
        "confidence: high\n"
        "sources: []\n"
        "related: []\n"
        "tags: [competitive]\n"
        'summary: "Shopify reporting research: plan availability, ShopifyQL, no Z report confirmed"\n'
        "---\n"
        "# Research — Shopify Reporting\n"
    )
    run_lint(wiki)
    catalog = wiki / "wiki/digests/catalog.md"
    assert catalog.exists(), "digests/catalog.md should be created by lint"
    content = catalog.read_text()
    assert "research-shopify-2026-05-07" in content
    assert "Shopify reporting research" in content


def test_digests_catalog_sorted_newest_first(wiki):
    """Digests catalog is sorted by last-updated descending."""
    from datetime import timedelta
    older = (date.today() - timedelta(days=60)).isoformat()
    for slug, date_str in [("research-a", older), ("research-b", TODAY)]:
        (wiki / f"wiki/digests/{slug}.md").write_text(
            f"---\ntype: source\nstatus: active\nlast-updated: {date_str}\n"
            "quarter: 2026-Q2\nokr: []\nconfidence: high\nsources: []\nrelated: []\n"
            f'tags: []\nsummary: "{slug} summary line that is long enough to pass"\n---\n# R\n'
        )
    run_lint(wiki)
    content = (wiki / "wiki/digests/catalog.md").read_text()
    pos_a = content.find("research-a")
    pos_b = content.find("research-b")
    assert pos_b < pos_a, "Newer digest (research-b) should appear before older (research-a)"


# ── Task 6: questions/catalog.md ─────────────────────────────────────────────

def _question_page(slug_name: str, status: str = "open", open_qs: int = 2,
                   summary: str = None) -> str:
    s = summary or f"{slug_name}: strategic question about domain requiring research to answer"
    return (
        "---\n"
        "type: question\n"
        f"status: {status}\n"
        f"last-updated: {TODAY}\n"
        "quarter: 2026-Q2\n"
        "okr: []\n"
        "confidence: low\n"
        "sources: []\n"
        "related: []\n"
        "tags: []\n"
        f'summary: "{s}"\n'
        "---\n"
        f"# {slug_name}\n\n"
        "## Sub-questions\n"
        + "".join(f"- [ ] Sub-question {i}\n" for i in range(open_qs))
    )


def test_question_type_valid(wiki):
    """type: question is a valid type even without schema.yaml."""
    questions_dir = wiki / "wiki/questions"
    questions_dir.mkdir()
    (questions_dir / "q-test.md").write_text(_question_page("q-test"))
    code, out, err = run_lint(wiki)
    assert "invalid type 'question'" not in err, f"question type rejected: {err}"


def test_invalid_question_status_is_schema_error(wiki):
    """A question page with an unrecognized status value is a schema error."""
    questions_dir = wiki / "wiki/questions"
    questions_dir.mkdir()
    bad = _question_page("q-bad").replace("status: open", "status: in-progress")
    (questions_dir / "q-bad.md").write_text(bad)
    code, out, err = run_lint(wiki)
    assert code == 2, f"Bad question status should be schema error, got {code}"
    assert "invalid status" in err


def test_questions_catalog_created(wiki):
    """lint.py creates wiki/questions/catalog.md when questions/ folder exists."""
    questions_dir = wiki / "wiki/questions"
    questions_dir.mkdir()
    (questions_dir / "q-cash-management.md").write_text(
        _question_page("q-cash-management", status="open", open_qs=3,
                       summary="Cash management F13: what the product needs for Z report; 3 sub-questions open")
    )
    run_lint(wiki)
    catalog = questions_dir / "catalog.md"
    assert catalog.exists()
    content = catalog.read_text()
    assert "q-cash-management" in content
    assert "?" in content  # open question gets ? prefix


def test_questions_catalog_not_created_without_folder(wiki):
    """If questions/ folder doesn't exist, catalog.md is not created."""
    run_lint(wiki)
    assert not (wiki / "wiki/questions/catalog.md").exists()
