#!/usr/bin/env python3
"""Pass A lint for the wiki. Python stdlib only.

Modes:
  python3 scripts/lint.py                    # full lint pass + health regen
  python3 scripts/lint.py --check-content PATH  # PII gate check on candidate file
"""
from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path


FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n(.*)\Z", re.DOTALL)
WIKILINK_RE = re.compile(r"\[\[([^\]]+)\]\]")


def _unwrap_item(item: str) -> str:
    """Strip optional quotes and extract wikilink slug if the item is a wikilink."""
    item = item.strip()
    if len(item) >= 2 and item[0] == item[-1] and item[0] in ('"', "'"):
        item = item[1:-1]
    m = WIKILINK_RE.match(item)
    if m:
        return m.group(1)
    return item


def parse_frontmatter(text: str) -> tuple[dict, str]:
    """Return (frontmatter_dict, body_text).

    Minimal YAML-ish parser — supports the subset we use:
    - `key: value` (string scalar)
    - `key: [item1, item2]` (inline list) or `key: []` (empty list)
    - Multi-line YAML list:
          key:
            - "[[slug]]"
            - plain-item
    - Wikilinks `[[slug]]` in list values are returned as plain slugs.

    This parser is intentionally limited to the frontmatter subset the schema
    uses. It's NOT a full YAML parser. The canonical format for wikilink lists
    is now multi-line (valid YAML; Obsidian Dataview parses it correctly).

    If no frontmatter, returns ({}, text).
    """
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}, text
    fm_text, body = m.group(1), m.group(2)
    fm: dict = {}
    lines = fm_text.splitlines()
    i = 0
    while i < len(lines):
        raw = lines[i]
        line = raw.rstrip()
        if not line or line.lstrip().startswith("#"):
            i += 1
            continue
        if ":" not in line:
            i += 1
            continue
        key, _, val = line.partition(":")
        key = key.strip()
        val = val.strip()

        # Multi-line list: `key:` with no value, followed by indented `- item` lines.
        if val == "":
            items: list = []
            j = i + 1
            while j < len(lines):
                nxt = lines[j]
                # List item must be indented and start with "- "
                if (nxt.startswith(" ") or nxt.startswith("\t")) and nxt.lstrip().startswith("- "):
                    item_text = nxt.lstrip()[2:].rstrip()
                    items.append(_unwrap_item(item_text))
                    j += 1
                elif nxt.strip() == "":
                    # Blank line inside a list — tolerate but don't consume
                    break
                else:
                    break
            if items:
                fm[key] = items
                i = j
                continue
            # `key:` with nothing after it → empty string scalar
            fm[key] = ""
            i += 1
            continue

        # Inline list [a, b] or []
        if val.startswith("[") and val.endswith("]"):
            items_str = val[1:-1].strip()
            if not items_str:
                fm[key] = []
            else:
                parts = [x.strip() for x in items_str.split(",")]
                fm[key] = [_unwrap_item(p) for p in parts]
            i += 1
            continue

        # Scalar
        fm[key] = val
        i += 1
    return fm, body


REQUIRED_FIELDS = [
    "type", "status", "last-updated",
    "quarter", "okr", "confidence",
    "sources", "related", "tags",
]

# Fields that are recommended but not required.
# Missing or too short → exit 1 warning, not exit 2 error.
# Synthesis pages (type: synthesis) are exempt.
RECOMMENDED_FIELDS = ["summary"]
SUMMARY_MIN_LEN = 40

CATALOG_AUTO_START = "<!-- AUTO-GENERATED by lint.py — do not edit this section -->"
CATALOG_AUTO_END = "<!-- END AUTO-GENERATED -->"

_CATALOG_EXCLUDED_TYPES = {"synthesis", "source"}


def check_recommended_fields(fm: dict, page_path: str) -> list[str]:
    """Return warning strings for missing or inadequate recommended fields.

    Synthesis pages are exempt — index, overview, glossary etc. don't need summaries.
    """
    if fm.get("type") == "synthesis":
        return []
    warnings: list[str] = []
    summary = fm.get("summary", "")
    if not summary:
        warnings.append(
            f"{page_path}: missing recommended field 'summary' "
            f"(add a one-line answer-preview: what question does this page answer?)"
        )
    elif len(str(summary).strip('"').strip("'")) < SUMMARY_MIN_LEN:
        warnings.append(
            f"{page_path}: summary too short ({len(str(summary).strip())} chars, "
            f"minimum {SUMMARY_MIN_LEN}) — be specific about what this page answers"
        )
    return warnings

_BUILTIN_TYPES = {
    "competitor", "initiative", "jtbd", "feature", "segment",
    "experiment", "metric", "decision", "source", "synthesis", "question",
    "session",
}

# ALLOWED_TYPES is populated at lint time from the wiki's CLAUDE.md.
# See load_allowed_types() — fallback is _BUILTIN_TYPES if CLAUDE.md is absent.
ALLOWED_TYPES = _BUILTIN_TYPES


def load_schema(wiki_root: Path) -> dict:
    """Parse schema.yaml if present. Returns dict with optional keys:
    - 'entity_types': set of valid type strings (always includes 'synthesis' and 'question')
    - 'domain': string domain name

    Returns empty dict if schema.yaml absent or unparseable.
    """
    schema_path = wiki_root / "schema.yaml"
    if not schema_path.exists():
        return {}
    text = schema_path.read_text()
    result: dict = {}
    entity_types: list = []
    in_entity_types = False
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("domain:"):
            result["domain"] = stripped[len("domain:"):].strip()
        elif stripped == "entity_types:":
            in_entity_types = True
        elif in_entity_types and stripped.startswith("- "):
            type_name = stripped[2:].strip()
            if type_name and " " not in type_name:
                entity_types.append(type_name)
        elif in_entity_types and not stripped.startswith("- ") and stripped:
            in_entity_types = False
    if entity_types:
        types = set(entity_types)
        types.add("synthesis")   # always valid
        types.add("question")    # always valid (added in Approach B)
        types.add("session")     # always valid (merge Phase 2)
        result["entity_types"] = types
    return result


def load_allowed_types(wiki_root: Path) -> set[str]:
    """Read entity types from the wiki's CLAUDE.md ## Entity types section.

    Handles two formats produced by different generations of the wiki template:

    Bullet list (new wikis):
        ## Entity types
        - tool
        - comparison

    Markdown table (legacy wiki format):
        ## Entity types
        | type | template | purpose |
        |---|---|---|
        | competitor | ... | ... |

    Falls back to _BUILTIN_TYPES if CLAUDE.md is absent or has no parseable
    ## Entity types section — keeps the tool working on legacy wikis.
    """
    schema = load_schema(wiki_root)
    if "entity_types" in schema:
        return schema["entity_types"]

    claude_md = wiki_root / "CLAUDE.md"
    if not claude_md.exists():
        return set(_BUILTIN_TYPES)

    text = claude_md.read_text()
    section_re = re.compile(
        r"^## Entity types\s*\n(.*?)(?=^## |\Z)", re.MULTILINE | re.DOTALL
    )
    m = section_re.search(text)
    if not m:
        return set(_BUILTIN_TYPES)

    types: set[str] = set()
    for line in m.group(1).splitlines():
        stripped = line.strip()
        # Bullet list format: "- type-name"
        if stripped.startswith("- ") and not stripped.startswith("- **"):
            type_name = stripped[2:].strip()
            if type_name and " " not in type_name:  # single-word type names only
                types.add(type_name)
        # Markdown table format: "| type-name | ..." — skip header/separator rows
        elif stripped.startswith("|") and not stripped.startswith("|---") and not stripped.startswith("| type"):
            first_col = stripped.split("|")[1].strip()
            # Strip backtick formatting if present, skip empty/header cells
            first_col = first_col.strip("`").strip()
            if first_col and " " not in first_col and first_col != "---":
                types.add(first_col)

    # Always include synthesis and question — reserved built-in types
    types.add("synthesis")
    types.add("question")
    types.add("session")
    return types if types else set(_BUILTIN_TYPES)

ALLOWED_STATUSES = {
    "active", "archived", "superseded", "draft",
    "running", "complete", "shipped", "planned", "deprecated",
    "cancelled", "reversed", "revisit-scheduled",
}

ALLOWED_QUESTION_STATUSES = {"open", "partial", "resolved", "blocked-internal"}

ALLOWED_CONFIDENCE = {"high", "med", "low"}

DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
QUARTER_RE = re.compile(r"^\d{4}-Q[1-4]$")


# --- Numeric-claim citation gate (merge Phase 2) ---------------------------
# A paragraph is COVERED if it carries any source tag from the taxonomy, a
# wikilink, a URL, or the explicit suppression marker %%[no-claim]%% (Obsidian
# comment syntax — invisible in reading view, greppable in source).
CLAIM_COVERAGE_RE = re.compile(
    r"\[(?:internal|external)::[a-z-]+\]"
    r"|\[hypothesis[^\]]*\]"
    r"|\[verified[:\s\]]"
    r"|\[REFUTED"
    r"|%%\[no-claim\]%%"
    r"|\[\["
    r"|https?://"
)
# Numbers that never count as claims on their own.
_CLAIM_ALLOWLIST = [
    re.compile(r"\b\d{4}-\d{2}-\d{2}\b"),   # dates
    re.compile(r"\b\d{4}-Q[1-4]\b"),        # quarters
    re.compile(r"\bv\d+(?:\.\d+)*\b"),      # versions
    re.compile(r"\b(?:19|20)\d{2}\b"),      # bare years
]
# What counts as a numeric claim: currency, percentages, magnitudes,
# multipliers, standalone integers >= 3 digits. Bare 1-2 digit integers are
# deliberately NOT claims ("3 options") — too noisy.
CLAIM_NUM_RE = re.compile(
    r"[$€£]\s?\d[\d,]*(?:\.\d+)?"
    r"|\b\d[\d,]*(?:\.\d+)?\s?%"
    r"|\b\d[\d,]*(?:\.\d+)?\s?(?:[KMB]\b|million\b|billion\b|thousand\b)"
    r"|\b\d+(?:\.\d+)?x\b"
    r"|\b\d{3,}(?:,\d{3})*\b"
)
_CLAIM_EXEMPT_TYPES = {"synthesis", "question"}


# --- Trust markup (merge Phase 2) -------------------------------------------
TRUST_VERIFIED_RE = re.compile(r"\[verified:?\s*(\d{4}-\d{2}-\d{2})?\]")
TRUST_HYPOTHESIS_RE = re.compile(r"\[hypothesis[^\]]*\]")
TRUST_REFUTED_RE = re.compile(r"\[REFUTED[^\]]*\]")


def trust_counts(body: str) -> dict:
    """Count claim-status markers in a page body."""
    verified = TRUST_VERIFIED_RE.findall(body)
    dates = sorted(d for d in verified if d)
    return {
        "verified": len(verified),
        "hypothesis": len(TRUST_HYPOTHESIS_RE.findall(body)),
        "refuted": len(TRUST_REFUTED_RE.findall(body)),
        "last_pass": dates[-1] if dates else "",
    }


def render_trust_line(counts: dict) -> str:
    line = (
        f"> Trust: {counts['verified']} verified · "
        f"{counts['hypothesis']} hypothesis · {counts['refuted']} refuted"
    )
    if counts["last_pass"]:
        line += f" — last verification pass {counts['last_pass']}"
    return line


def _find_real_trust_line(lines: list[str]) -> int | None:
    """Return the index of the first NON-fenced line starting '> Trust:'.

    Fence-aware: lines inside ``` code blocks are never matched, so a fenced
    example containing '> Trust: ...' (e.g. in docs) is left alone.
    """
    in_fence = False
    for i, line in enumerate(lines):
        if line.strip().startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        if line.startswith("> Trust:"):
            return i
    return None


def upsert_trust_line(md_path: Path) -> bool:
    """Insert, update, or remove the human-visible trust line under the first H1.

    - When total markers > 0: insert or update the trust line.
    - When total markers == 0 AND trust line exists: remove it (plus one adjacent blank if needed).
    - When total markers == 0 AND no trust line: no-op (return False).
    Returns True if the file changed.

    Matching is fence-aware and line-by-line (not a whole-file regex): a fenced
    code example containing a '> Trust: ...' line is never treated as the real
    trust line, so it's neither rewritten nor mistaken for the real one.
    """
    text = md_path.read_text()
    m = FRONTMATTER_RE.match(text)
    body = m.group(2) if m else text
    counts = trust_counts(body)
    total = counts["verified"] + counts["hypothesis"] + counts["refuted"]

    lines = text.splitlines()
    trailing_newline = "\n" if text.endswith("\n") else ""

    # Case 1: markers present — insert or update trust line
    if total > 0:
        new_line = render_trust_line(counts)
        ti = _find_real_trust_line(lines)
        if ti is not None:
            # Update existing trust line
            if lines[ti] == new_line:
                return False
            lines[ti] = new_line
            new_text = "\n".join(lines) + trailing_newline
        else:
            # Insert new trust line after H1
            h1 = next((i for i, l in enumerate(lines) if l.startswith("# ")), None)
            if h1 is None:
                return False
            # Insert blank line before trust line, then the trust line itself
            lines.insert(h1 + 1, "")
            lines.insert(h1 + 2, new_line)
            # Ensure blank line after trust line if next line is non-blank
            if h1 + 3 < len(lines) and lines[h1 + 3].strip():
                lines.insert(h1 + 3, "")
            new_text = "\n".join(lines) + trailing_newline
        if new_text != text:
            md_path.write_text(new_text)
            return True
        return False

    # Case 2: zero markers — remove stale trust line if present
    ti = _find_real_trust_line(lines)
    if ti is not None:
        # Remove the trust line
        lines.pop(ti)
        # If removal would leave two consecutive blank lines, remove one
        if ti < len(lines) and ti > 0 and lines[ti - 1].strip() == "" and lines[ti].strip() == "":
            lines.pop(ti)
        new_text = "\n".join(lines) + trailing_newline
        if new_text != text:
            md_path.write_text(new_text)
            return True
    return False


# --- Readability checks (merge Phase 2) --------------------------------------
_NAV_SLUGS = {"index", "overview", "glossary", "people"}
_BOTTOM_LINE_TYPES = {"initiative", "segment", "synthesis"}
_SECTION_MIN_CHARS = 40


def _section_content(body: str, heading: str) -> str:
    """Text of a `## heading` section with HTML comments stripped; '' if absent."""
    m = re.search(
        rf"^## {re.escape(heading)}\s*$(.*?)(?=^## |\Z)",
        body, re.MULTILINE | re.DOTALL,
    )
    if not m:
        return ""
    return re.sub(r"<!--.*?-->", "", m.group(1), flags=re.DOTALL).strip()


def check_bottom_line(pages: dict[str, dict]) -> list[str]:
    """Content synthesis/initiative/segment pages open with a position statement."""
    out: list[str] = []
    for slug, page in pages.items():
        if page["fm"].get("type") not in _BOTTOM_LINE_TYPES:
            continue
        tail = slug.rsplit("/", 1)[-1]
        if tail in _NAV_SLUGS or tail == "catalog" or slug.startswith("log/"):
            continue
        if len(_section_content(page["body"], "Bottom line")) < _SECTION_MIN_CHARS:
            out.append(
                f"{page['path']}: missing or thin '## Bottom line' section — "
                f"open with a 2-4 sentence position statement (what we believe and why it matters)"
            )
    return out


def check_overview(pages: dict[str, dict]) -> list[str]:
    """overview.md must state current theses and must not be a bare link list."""
    page = pages.get("overview")
    if not page:
        return []
    out: list[str] = []
    if len(_section_content(page["body"], "Current theses")) < _SECTION_MIN_CHARS:
        out.append(
            "overview.md: '## Current theses' missing or empty — the overview must "
            "state what the project currently believes"
        )
    content_lines = [
        l.strip() for l in page["body"].splitlines()
        if l.strip() and not l.strip().startswith(("#", "<!--", "> "))
    ]
    if content_lines and all(
        l.startswith(("-", "*")) and ("[[" in l or "](" in l) for l in content_lines
    ):
        out.append(
            "overview.md: body is a link list, not an overview — add narrative "
            "synthesis (theses, what changed, top entities)"
        )
    return out


def _paragraphs(body: str):
    """Yield (first_line_no, text) for prose paragraphs.

    Skips fenced code blocks, headings, table rows, and the trust line
    ('> Trust: ...'). The trust line is lint-generated output, not user prose
    — including it would let lint's own numeric summary (e.g. "120 verified")
    trip the untagged-claim gate on the next run, an unrecoverable
    self-inflicted failure. Paragraphs are blocks of consecutive non-skipped
    lines separated by blank lines.
    """
    paras: list[tuple[int, str]] = []
    cur: list[str] = []
    start: int | None = None
    in_fence = False
    for n, line in enumerate(body.splitlines(), 1):
        s = line.strip()
        if s.startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence or s.startswith("#") or s.startswith("|") or s.startswith("> Trust:"):
            continue
        if not s:
            if cur:
                paras.append((start, "\n".join(cur)))
                cur, start = [], None
            continue
        if start is None:
            start = n
        cur.append(line)
    if cur:
        paras.append((start, "\n".join(cur)))
    return paras


def find_untagged_claims(
    body: str, page_path: str, ptype: str, line_offset: int = 0
) -> list[str]:
    """Return one finding per uncovered paragraph containing a numeric claim.

    `line_offset` shifts reported line numbers from body-relative to
    file-relative (the number of lines consumed by the frontmatter block),
    so findings point at the actual line in the file rather than into the
    body alone.
    """
    if ptype in _CLAIM_EXEMPT_TYPES:
        return []
    findings: list[str] = []
    for line_no, para in _paragraphs(body):
        if CLAIM_COVERAGE_RE.search(para):
            continue
        scrubbed = re.sub(r"`[^`]*`", "", para)   # inline code is not prose
        for pat in _CLAIM_ALLOWLIST:
            scrubbed = pat.sub("", scrubbed)
        m = CLAIM_NUM_RE.search(scrubbed)
        if m:
            findings.append(
                f"{page_path}: line {line_no + line_offset}: untagged numeric claim '{m.group(0).strip()}' "
                f"— add a source tag, [[wikilink]], URL, or %%[no-claim]%%"
            )
    return findings


def validate_frontmatter(
    fm: dict, page_path: str, allowed_types: set[str] | None = None
) -> list[str]:
    """Return a list of error strings. Empty list = valid.

    allowed_types defaults to the global ALLOWED_TYPES (builtin set) when not
    supplied — preserved for callers that don't have wiki_root context (e.g.
    --check-content mode). full_lint() always passes the wiki-specific set.
    """
    if allowed_types is None:
        allowed_types = ALLOWED_TYPES
    errors: list[str] = []
    for field in REQUIRED_FIELDS:
        if field not in fm:
            errors.append(f"{page_path}: missing required field '{field}'")
    if fm.get("type") and fm["type"] not in allowed_types:
        errors.append(f"{page_path}: invalid type '{fm['type']}'")
    if fm.get("type") == "question":
        # Question pages use their own status vocabulary; skip generic status check
        q_status = fm.get("status", "")
        if q_status and q_status not in ALLOWED_QUESTION_STATUSES:
            errors.append(
                f"{page_path}: invalid status '{q_status}' for question type "
                f"(allowed: {', '.join(sorted(ALLOWED_QUESTION_STATUSES))})"
            )
    elif fm.get("status") and fm["status"] not in ALLOWED_STATUSES:
        errors.append(f"{page_path}: invalid status '{fm['status']}'")
    if fm.get("confidence") and fm["confidence"] not in ALLOWED_CONFIDENCE:
        errors.append(f"{page_path}: invalid confidence '{fm['confidence']}'")
    # Date format validation — prevents sentinel values like "TBD" from slipping past.
    # `is_stale` silently returns False for unparseable dates, so without this check
    # a template-copied page with `last-updated: TBD` would never be flagged as stale.
    # Templates themselves live in _templates/ (not under wiki/) so they're not scanned.
    lu = fm.get("last-updated")
    if lu and not DATE_RE.match(str(lu)):
        errors.append(f"{page_path}: invalid last-updated '{lu}' (expected YYYY-MM-DD)")
    q = fm.get("quarter")
    if q and not QUARTER_RE.match(str(q)):
        errors.append(f"{page_path}: invalid quarter '{q}' (expected YYYY-QN)")
    return errors


def check_author(fm: dict, page_path: str) -> list[str]:
    """session and decision pages must attribute their content: non-empty author list."""
    if fm.get("type") not in ("session", "decision"):
        return []
    author = fm.get("author")
    if isinstance(author, str):
        author = [author] if author.strip() and author.strip() != '""' else []
    if not author:
        return [
            f"{page_path}: type '{fm.get('type')}' requires non-empty 'author' list "
            f"(who produced/decided this)"
        ]
    return []


def check_confidence_vs_sources(fm: dict, page_path: str) -> list[str]:
    """Entity pages with zero sources may declare at most confidence: low.

    synthesis (navigational) and question (inherently unsourced) are exempt.
    """
    if fm.get("type") in ("synthesis", "question"):
        return []
    sources = fm.get("sources") or []
    if isinstance(sources, str):
        sources = [sources] if sources.strip() and sources.strip() != '""' else []
    sources = [s for s in sources if str(s).strip().strip('"').strip("'")]
    conf = fm.get("confidence", "")
    if not sources and conf in ("high", "med"):
        return [
            f"{page_path}: sources is empty but confidence is '{conf}' — "
            f"source-less pages are capped at confidence: low"
        ]
    return []


_DIGEST_BADNAME_RE = re.compile(r"(-v\d+(?:\.\d+)*$)|(\bsession\b)", re.IGNORECASE)


def check_digest_names(pages: dict[str, dict]) -> list[str]:
    """Digests must be topic-named, not session/version-named (AI Factory rule #4)."""
    out: list[str] = []
    for slug, page in pages.items():
        if page["fm"].get("type") != "source" or "digests/" not in slug:
            continue
        tail = slug.rsplit("/", 1)[-1]
        if tail == "catalog":
            continue
        if _DIGEST_BADNAME_RE.search(tail):
            out.append(
                f"{page['path']}: digest name '{tail}' looks session/version-based — "
                f"rename to a topic-based name"
            )
    return out


# Root files that are infrastructure, never strays.
_STRAY_ALLOWED_ROOT = {"README.md", "CLAUDE.md", "AGENTS.md", "GEMINI.md"}


def find_stray_files(wiki_root: Path) -> list[str]:
    """Top-level *.md files outside wiki/ or raw/ are ingest-pending strays.

    raw/ is ALWAYS a correct drop location (zero ceremony) and is never scanned.
    """
    return sorted(
        md.name for md in wiki_root.glob("*.md")
        if md.name not in _STRAY_ALLOWED_ROOT
    )


def find_dead_refs(pages: dict[str, dict]) -> list[str]:
    """sources:/related: entries that resolve to no page (by slug or tail).

    Skipped: raw/ paths, relative/absolute paths, URLs — those are checked by
    validate_external_refs or are legitimately outside the wiki page set.
    """
    known: set[str] = set()
    for slug in pages:
        known.add(slug)
        known.add(slug.rsplit("/", 1)[-1])
    out: list[str] = []
    for slug, page in pages.items():
        for field in ("sources", "related"):
            refs = page["fm"].get(field) or []
            if isinstance(refs, str):
                refs = [refs] if refs.strip() and refs.strip() != '""' else []
            for ref in refs:
                r = _unwrap_item(str(ref)).strip()
                if not r or r.startswith(("raw/", "../", "~", "/")) or "://" in r:
                    continue
                if r not in known and r.rsplit("/", 1)[-1] not in known:
                    out.append(f"{page['path']}: dead {field} ref '{r}' — no such page")
    return sorted(out)


from datetime import date, timedelta

STALE_AFTER_DAYS = 90


def _current_quarter() -> str:
    """Return current quarter in YYYY-QN format."""
    today = date.today()
    q = (today.month - 1) // 3 + 1
    return f"{today.year}-Q{q}"


def is_stale(fm: dict, today: date | None = None) -> bool:
    """True if status=active AND last-updated is more than STALE_AFTER_DAYS old."""
    if fm.get("status") != "active":
        return False
    raw = fm.get("last-updated")
    if not raw:
        return False
    try:
        y, m, d = map(int, str(raw).split("-"))
        last = date(y, m, d)
    except (ValueError, AttributeError):
        return False
    today = today or date.today()
    return (today - last) > timedelta(days=STALE_AFTER_DAYS)


def _catalog_prefix(fm: dict, open_questions: int, today: date) -> str:
    """Return ✓, △, or ? prefix for a §Agent Catalog entry.

    ✓ = confidence high|med, not stale, zero open questions
    △ = stale (>90d active), confidence low, or has open questions
    """
    if not fm:
        return "?"
    confidence = fm.get("confidence", "")
    tags = fm.get("tags") or []
    if is_stale(fm, today) or confidence == "low" or "unverified" in tags or open_questions > 0:
        return "△"
    return "✓"


def generate_start_here(pages: dict[str, dict]) -> str:
    """A 5-link reading path for humans: the index's front door."""
    items: list[str] = []
    if "overview" in pages:
        items.append("[[overview]] — current synthesis")

    def _newest(ptype: str, by_tail: bool):
        cands = [(s, p) for s, p in pages.items() if p["fm"].get("type") == ptype]
        if ptype == "source":
            cands = [
                (s, p) for s, p in cands
                if "digests/" in s and s.rsplit("/", 1)[-1] != "catalog"
            ]
        if not cands:
            return None
        if by_tail:
            cands.sort(key=lambda sp: sp[0].rsplit("/", 1)[-1], reverse=True)
        else:
            cands.sort(key=lambda sp: sp[1]["fm"].get("last-updated", ""), reverse=True)
        return cands[0][0].rsplit("/", 1)[-1]

    d = _newest("decision", by_tail=True)   # date-prefixed filenames sort chronologically
    if d:
        items.append(f"[[{d}]] — newest decision")
    open_qs = [
        (s, p) for s, p in pages.items()
        if p["fm"].get("type") == "question" and p["fm"].get("status") == "open"
    ]
    if open_qs:
        open_qs.sort(key=lambda sp: sp[1]["fm"].get("last-updated", ""), reverse=True)
        items.append(f"[[{open_qs[0][0].rsplit('/', 1)[-1]}]] — top open question")
    s = _newest("session", by_tail=True)
    if s:
        items.append(f"[[{s}]] — latest session")
    dg = _newest("source", by_tail=False)
    if dg:
        items.append(f"[[{dg}]] — newest digest")

    lines = ["## Start here"]
    for i, item in enumerate(items, 1):
        lines.append(f"{i}. {item}")
    return "\n".join(lines)


def generate_agent_catalog(pages: dict[str, dict], today: date | None = None) -> str:
    """Build the §Agent Catalog markdown block from page frontmatter and summaries.

    Groups entity pages by type (sorted newest first within each group).
    Question pages get their own section at the end.
    Excludes synthesis and source types.
    Returns the block text (without the AUTO-GENERATED markers).
    """
    today = today or date.today()
    entity_pages: dict[str, dict] = {}
    question_pages: dict[str, dict] = {}
    session_pages: dict[str, dict] = {}
    deliverable_pages: dict[str, dict] = {}
    for slug, page in pages.items():
        fm = page.get("fm", {})
        ptype = fm.get("type", "")
        ext_ref = str(fm.get("external-ref", "")).strip('"').strip("'")
        if ptype == "source" and ext_ref:
            deliverable_pages[slug] = page
            continue
        if ptype in _CATALOG_EXCLUDED_TYPES:
            continue
        if ptype == "question":
            question_pages[slug] = page
        elif ptype == "session":
            session_pages[slug] = page
        elif ptype:
            entity_pages[slug] = page

    lines: list[str] = ["## Agent Catalog"]

    by_type: dict[str, list] = {}
    for slug, page in entity_pages.items():
        ptype = page["fm"].get("type", "unknown")
        by_type.setdefault(ptype, []).append((slug, page))

    for ptype in sorted(by_type):
        group = by_type[ptype]
        if ptype == "decision":
            group.sort(key=lambda sp: sp[0].rsplit("/", 1)[-1], reverse=True)
        else:
            group.sort(key=lambda sp: sp[1]["fm"].get("last-updated", ""), reverse=True)
        lines.append(f"\n### {ptype.capitalize()}s ({len(group)})")
        for slug, page in group:
            fm = page["fm"]
            open_qs = page.get("open_questions", 0)
            prefix = _catalog_prefix(fm, open_qs, today)
            tail = slug.rsplit("/", 1)[-1]
            summary = str(fm.get("summary", "")).strip('"').strip("'")
            tags = fm.get("tags") or []
            confidence = fm.get("confidence", "")
            tag_str = f" [{', '.join(tags)}]" if tags else ""
            t = page.get("trust") or {}
            if (t.get("verified", 0) + t.get("hypothesis", 0) + t.get("refuted", 0)) > 0:
                conf_str = f" trust:{t['verified']}✓/{t['hypothesis']}~/{t['refuted']}✗"
            else:
                conf_str = f" confidence:{confidence}" if confidence else ""
            qs_str = f" open-Qs:{open_qs}" if open_qs > 0 else ""
            summary_part = f" — {summary}" if summary else ""
            lines.append(f"{prefix} [[{tail}]]{summary_part}{tag_str}{conf_str}{qs_str}")

    if session_pages:
        lines.append(f"\n### Sessions ({len(session_pages)})")
        ordered = sorted(session_pages.items(), key=lambda sp: sp[0].rsplit("/", 1)[-1], reverse=True)
        for slug, page in ordered:
            fm = page["fm"]
            tail = slug.rsplit("/", 1)[-1]
            summary = str(fm.get("summary", "")).strip('"').strip("'")
            summary_part = f" — {summary}" if summary else ""
            lines.append(f"- [[{tail}]]{summary_part}")

    if deliverable_pages:
        lines.append(f"\n### External deliverables ({len(deliverable_pages)})")
        ordered = sorted(
            deliverable_pages.items(),
            key=lambda sp: sp[1]["fm"].get("last-updated", ""), reverse=True,
        )
        for slug, page in ordered:
            fm = page["fm"]
            tail = slug.rsplit("/", 1)[-1]
            summary = str(fm.get("summary", "")).strip('"').strip("'")
            ext = str(fm.get("external-ref", "")).strip('"').strip("'")
            summary_part = f" — {summary}" if summary else ""
            lines.append(f"📎 [[{tail}]]{summary_part} ({ext})")

    if question_pages:
        open_count = sum(1 for p in question_pages.values() if p["fm"].get("status") == "open")
        partial_count = sum(1 for p in question_pages.values() if p["fm"].get("status") in ("partial", "blocked-internal"))
        resolved_count = sum(1 for p in question_pages.values() if p["fm"].get("status") == "resolved")
        lines.append(f"\n### Open Questions ({open_count} open, {partial_count} partial, {resolved_count} resolved)")
        for slug, page in sorted(question_pages.items(), key=lambda sp: sp[1]["fm"].get("last-updated", ""), reverse=True):
            fm = page["fm"]
            status = fm.get("status", "open")
            open_qs = page.get("open_questions", 0)
            if status == "open":
                prefix = "?"
            elif status == "resolved":
                prefix = "✓"
            else:
                prefix = "△"
            tail = slug.rsplit("/", 1)[-1]
            summary = str(fm.get("summary", "")).strip('"').strip("'")
            tags = fm.get("tags") or []
            tag_str = f" [{', '.join(tags)}]" if tags else ""
            summary_part = f" — {summary}" if summary else ""
            lines.append(f"{prefix} [[{tail}]]{summary_part}{tag_str} {status}")

    return "\n".join(lines)


def update_index_catalog(wiki_root: Path, catalog_text: str) -> None:
    """Write the §Agent Catalog block into wiki/index.md between AUTO-GENERATED markers.

    If markers don't exist yet, inserts after the YAML frontmatter closing ---.
    Preserves all other content.
    """
    index_path = wiki_root / "wiki" / "index.md"
    if not index_path.exists():
        return
    content = index_path.read_text()
    new_block = f"{CATALOG_AUTO_START}\n{catalog_text}\n{CATALOG_AUTO_END}"
    pattern = re.compile(
        re.escape(CATALOG_AUTO_START) + r".*?" + re.escape(CATALOG_AUTO_END),
        re.DOTALL,
    )
    if pattern.search(content):
        index_path.write_text(pattern.sub(new_block, content))
        return
    # No markers — insert after closing frontmatter ---
    lines = content.split("\n")
    if lines and lines[0].strip() == "---":
        close = next(
            (i for i, ln in enumerate(lines[1:], 1) if ln.strip() == "---"), None
        )
        if close is not None:
            lines.insert(close + 1, "")
            lines.insert(close + 1, CATALOG_AUTO_END)
            lines.insert(close + 1, catalog_text)
            lines.insert(close + 1, CATALOG_AUTO_START)
            index_path.write_text("\n".join(lines))
            return
    index_path.write_text(new_block + "\n\n" + content)


def generate_digests_catalog(pages: dict[str, dict]) -> str:
    """Build wiki/digests/catalog.md — one summary line per digest, newest first.

    Only includes pages with type: source that live under wiki/digests/.
    """
    digests = [
        (slug, page) for slug, page in pages.items()
        if page["fm"].get("type") == "source" and "digests/" in slug
    ]
    digests.sort(key=lambda sp: sp[1]["fm"].get("last-updated", ""), reverse=True)

    lines = [
        "---",
        "type: synthesis",
        "status: active",
        f"last-updated: {date.today().isoformat()}",
        f"as-of: {date.today().isoformat()}",
        f"quarter: {_current_quarter()}",
        "okr: []",
        "confidence: high",
        "sources: []",
        "related: []",
        "tags: []",
        "---",
        "# Digest Catalog",
        "",
        "Auto-generated by lint.py. One entry per research digest, newest first.",
        "",
    ]
    for slug, page in digests:
        fm = page["fm"]
        tail = slug.rsplit("/", 1)[-1]
        summary = str(fm.get("summary", "")).strip('"').strip("'")
        lu = fm.get("last-updated", "")
        tags = fm.get("tags") or []
        tag_str = f" [{', '.join(tags)}]" if tags else ""
        summary_part = f" — {summary}" if summary else ""
        lines.append(f"- [[{tail}]]{summary_part}{tag_str} ({lu})")

    return "\n".join(lines)


def generate_questions_catalog(pages: dict[str, dict]) -> str:
    """Build wiki/questions/catalog.md — one line per question page.

    Open questions first, grouped by status (open → partial/blocked-internal → resolved).
    Within each status group, newest first.
    Open questions use ? prefix; partial/blocked-internal use △; resolved use ✓.
    """
    question_pages = [
        (slug, page) for slug, page in pages.items()
        if page["fm"].get("type") == "question"
    ]
    # Sort by date descending (newest first) within each status group
    question_pages.sort(
        key=lambda sp: sp[1]["fm"].get("last-updated", ""),
        reverse=True,
    )
    # Then sort by status: open (0) < partial/blocked-internal (1) < resolved (2)
    # This is a stable sort, so date order is preserved within each status
    question_pages.sort(
        key=lambda sp: {
            "open": 0,
            "partial": 1,
            "blocked-internal": 1,
            "resolved": 2,
        }.get(sp[1]["fm"].get("status", "open"), 3),
    )
    lines = [
        "---",
        "type: synthesis",
        "status: active",
        f"last-updated: {date.today().isoformat()}",
        f"as-of: {date.today().isoformat()}",
        f"quarter: {_current_quarter()}",
        "okr: []",
        "confidence: high",
        "sources: []",
        "related: []",
        "tags: []",
        "---",
        "# Questions Catalog",
        "",
        "Auto-generated by lint.py. Strategic open and resolved questions.",
        "",
    ]
    for slug, page in question_pages:
        fm = page["fm"]
        status = fm.get("status", "open")
        open_qs = page.get("open_questions", 0)
        if status == "open":
            prefix = "?"
        elif status == "resolved":
            prefix = "✓"
        else:
            prefix = "△"
        tail = slug.rsplit("/", 1)[-1]
        summary = str(fm.get("summary", "")).strip('"').strip("'")
        tags = fm.get("tags") or []
        tag_str = f" [{', '.join(tags)}]" if tags else ""
        sq_str = f" sub-Qs:{open_qs}" if open_qs > 0 else ""
        summary_part = f" — {summary}" if summary else ""
        lines.append(f"{prefix} [[{tail}]]{summary_part}{tag_str}{sq_str} ({status})")
    return "\n".join(lines)


def find_unacknowledged_digests(pages: dict[str, dict]) -> list[tuple[str, str]]:
    """Return (entity_slug, digest_slug) pairs where a digest's `related:` names an
    entity page but that entity page's `sources:` does not list the digest back.

    This enforces the compounding contract: digest → entity (via related:) must be
    mirrored by entity → digest (via sources:). Broken pairs mean the entity page was
    not enriched after the digest was ingested.

    Only checks digests (type: source) against non-source, non-synthesis entity pages.
    """
    missing: list[tuple[str, str]] = []
    for slug, page in pages.items():
        fm = page.get("fm", {})
        if fm.get("type") != "source":
            continue
        digest_tail = slug.rsplit("/", 1)[-1]
        related = fm.get("related") or []
        for ref in related:
            ref_slug = _unwrap_item(str(ref))
            # Find matching entity page (exact slug match or tail match)
            for entity_slug, entity_page in pages.items():
                etype = entity_page.get("fm", {}).get("type")
                if etype in ("source", "synthesis"):
                    continue
                entity_tail = entity_slug.rsplit("/", 1)[-1]
                if entity_slug != ref_slug and entity_tail != ref_slug:
                    continue
                # Found the entity page — check its sources: list
                entity_sources = entity_page.get("fm", {}).get("sources") or []
                entity_source_slugs = {_unwrap_item(str(s)) for s in entity_sources}
                if slug not in entity_source_slugs and digest_tail not in entity_source_slugs:
                    missing.append((entity_slug, slug))
                break
    return sorted(missing)


def validate_external_refs(pages: dict[str, dict], wiki_root: Path) -> list[str]:
    """Check that external-ref fields point to resolvable targets.

    Returns warning strings (not errors) — broken cross-wiki refs are exit 1, not exit 2.
    Supports two URI formats:
    - wiki://domain/slug  →  resolved via resolve_wiki.py resolve-uri
    - /absolute/path/to/file.md or ~/...  →  checked via Path.exists()
    """
    import subprocess

    warnings: list[str] = []

    # Locate resolve_wiki.py: try <wiki_root>/../plugin/scripts/ first, then CLAUDE_PLUGIN_ROOT env
    resolve_script = wiki_root.parent / "plugin" / "scripts" / "resolve_wiki.py"
    if not resolve_script.exists():
        plugin_root = os.environ.get("CLAUDE_PLUGIN_ROOT", "")
        if plugin_root:
            resolve_script = Path(plugin_root) / "scripts" / "resolve_wiki.py"

    for slug, page in pages.items():
        ext_ref = page.get("fm", {}).get("external-ref", "")
        if not ext_ref or ext_ref == '""' or ext_ref.strip('"') == "":
            continue
        ext_ref = ext_ref.strip('"').strip("'")

        if ext_ref.startswith("wiki://"):
            if not resolve_script.exists():
                warnings.append(
                    f"{slug}: external-ref '{ext_ref}' cannot be validated "
                    f"— resolve_wiki.py not found"
                )
                continue
            result = subprocess.run(
                ["python3", str(resolve_script), "resolve-uri", ext_ref],
                capture_output=True, text=True
            )
            if result.returncode != 0:
                warnings.append(
                    f"{slug}: external-ref '{ext_ref}' cannot be resolved "
                    f"— domain not in registry"
                )
            else:
                target = Path(result.stdout.strip())
                if not target.exists():
                    warnings.append(
                        f"{slug}: external-ref '{ext_ref}' resolves to "
                        f"'{target}' but file not found"
                    )
        elif ext_ref.startswith("/") or ext_ref.startswith("~"):
            target = Path(ext_ref.replace("~", str(Path.home())))
            if not target.exists():
                warnings.append(f"{slug}: external-ref '{ext_ref}' not found")

    return warnings


_BUDGET_ENTITY_PAGE = 12_000
_RESEARCH_PREFIXES = ("research-", "synthesis-", "validation-")


def check_evolution_triggers(pages: dict[str, dict], wiki_root: Path) -> list[str]:
    """Return warning strings for evolution triggers.

    Checks:
    1. Entity or question pages over _BUDGET_ENTITY_PAGE chars
    2. Research/digest files in wiki/ root (not in wiki/digests/)
    """
    warnings: list[str] = []
    wiki_dir = wiki_root / "wiki"
    for slug, page in pages.items():
        fm = page.get("fm", {})
        ptype = fm.get("type", "")
        if ptype in ("synthesis", "source"):
            continue
        page_path = wiki_dir / page["path"]
        if page_path.exists():
            char_count = page_path.stat().st_size
            if char_count > _BUDGET_ENTITY_PAGE:
                warnings.append(
                    f"{page['path']}: oversize ({char_count:,} chars, budget {_BUDGET_ENTITY_PAGE:,}) "
                    f"— consider splitting or archiving older sections"
                )
    # Check for misplaced research files in wiki/ root (top-level only, not subdirs)
    for md in wiki_dir.glob("*.md"):
        rel = md.relative_to(wiki_dir)
        if rel.parts[0].startswith("_"):
            continue
        name = md.stem
        if any(name.startswith(p) for p in _RESEARCH_PREFIXES):
            warnings.append(
                f"wiki/{name}.md: looks like a digest/research file — "
                f"move to wiki/digests/ and set type: source"
            )
            continue
        # Also flag type: source pages not in digests/
        try:
            text = md.read_text(errors="ignore")
            if text.startswith("---") and "\ntype: source\n" in text[:200]:
                warnings.append(
                    f"wiki/{name}.md: type: source found in wiki/ root — "
                    f"move to wiki/digests/"
                )
        except OSError:
            pass
    return warnings


def find_orphans(pages: dict[str, dict]) -> list[str]:
    """Return slugs with zero inbound references.

    Inbound = either a [[wikilink]] in another page's body OR a slug in another
    page's frontmatter `sources`/`related` lists. Obsidian's shortest-path
    resolution is approximated: a reference `[[tail]]` matches any slug whose
    final path component is `tail` (e.g. `[[2026-Q2]]` matches `log/2026-Q2`).

    Pages with type in {source, synthesis} are excluded:
    - source: digests legitimately have no inbound
    - synthesis: index/overview/glossary/people/log are navigational, not entities
    """
    referenced: set[str] = set()
    for slug, page in pages.items():
        body = page.get("body", "")
        for m in WIKILINK_RE.finditer(body):
            referenced.add(m.group(1))
        for list_field in ("sources", "related"):
            for ref in page.get("fm", {}).get(list_field, []) or []:
                referenced.add(ref)

    # Approximate Obsidian's shortest-path wikilink resolution: a reference to
    # just the tail (e.g. "2026-Q2") should count as an inbound for any slug
    # ending with "/2026-Q2".
    orphans = []
    for slug, page in pages.items():
        if page.get("fm", {}).get("type") in ("source", "synthesis"):
            continue
        tail = slug.rsplit("/", 1)[-1]
        if slug in referenced or tail in referenced:
            continue
        orphans.append(slug)
    return sorted(orphans)


PII_PATTERNS = {
    "email":      re.compile(r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b"),
    # phone_us requires MANDATORY separators between the three digit groups to avoid
    # false positives on order IDs like "order-6501234567" that contain embedded 10-digit
    # runs. Bare 10-digit phone numbers without separators are handled by the blocklist
    # path, not the regex.
    "phone_us":   re.compile(r"\b(?:\+?1[-.\s])?\(?\d{3}\)?[-.\s]\d{3}[-.\s]\d{4}\b"),
    "phone_intl": re.compile(r"\+\d{1,3}[-.\s]\d{3,14}"),
    "ssn":        re.compile(r"\b\d{3}-\d{2}-\d{4}\b"),
    "url_pii":    re.compile(r"https?://\S+?[?&](?:email|phone|token|user)=\S+"),
}


def scan_pii(content: str, blocklist: set[str]) -> list[dict]:
    """Return a list of matches. Each match: {pattern, match_text, start, end}."""
    matches: list[dict] = []
    for name, pat in PII_PATTERNS.items():
        for m in pat.finditer(content):
            matches.append({
                "pattern": name,
                "match_text": m.group(0),
                "start": m.start(),
                "end": m.end(),
            })
    # Case-insensitive blocklist matching — LLM stage-1 scrubs may produce
    # inconsistent casing (e.g. "sarah johnson" vs "Sarah Johnson").
    for entry in blocklist:
        if not entry:
            continue
        pat = re.compile(re.escape(entry), re.IGNORECASE)
        for m in pat.finditer(content):
            matches.append({
                "pattern": "blocklist",
                "match_text": m.group(0),
                "start": m.start(),
                "end": m.end(),
            })
    return matches


def load_blocklist(wiki_root: Path) -> set[str]:
    """Load the PII blocklist if it exists; empty set if not."""
    bl_path = wiki_root / "wiki" / "_pii" / "blocklist.txt"
    if not bl_path.exists():
        return set()
    return {line.strip() for line in bl_path.read_text().splitlines() if line.strip() and not line.startswith("#")}


def check_content_cmd(content_path: Path, wiki_root: Path) -> int:
    """Gate: scan a candidate content file. Exit non-zero if any PII found."""
    if not content_path.exists():
        print(f"error: {content_path} not found", file=sys.stderr)
        return 2
    text = content_path.read_text()
    blocklist = load_blocklist(wiki_root)
    matches = scan_pii(text, blocklist)
    if not matches:
        print(f"OK: no PII detected in {content_path}")
        return 0
    print(f"PII detected in {content_path}:")
    for m in matches:
        print(f"  [{m['pattern']}] {m['match_text']}")
    return 1


from collections import Counter


def render_health(
    pages: dict[str, dict],
    stale_count: int,
    orphan_count: int,
    today: date | None = None,
    dead_refs: int = 0,
    untagged_claims: int = 0,
    strays: int = 0,
    stale_slugs: list[str] | None = None,
) -> str:
    """Render the _health.md content."""
    today = today or date.today()
    types = Counter(p.get("fm", {}).get("type", "unknown") for p in pages.values())
    statuses = Counter(p.get("fm", {}).get("status", "unknown") for p in pages.values())
    lines = [
        "---",
        "type: synthesis",
        "status: active",
        f"last-updated: {today.isoformat()}",
        f"as-of: {today.isoformat()}",
        "---",
        "# Wiki Health",
        "",
        f"Generated: {today.isoformat()}",
        f"Total pages: {len(pages)}",
        "",
        "## By type",
    ]
    for t in sorted(types):
        lines.append(f"- {t}: {types[t]}")
    lines.append("")
    lines.append("## By status")
    for s in sorted(statuses):
        lines.append(f"- {s}: {statuses[s]}")
    lines.append("")
    lines.append("## Signals")
    lines.append(f"- Stale: {stale_count}")
    lines.append(f"- Orphans: {orphan_count}")
    lines.append(f"- Dead refs: {dead_refs}")
    lines.append(f"- Untagged claims: {untagged_claims}")
    lines.append(f"- Stray files: {strays}")
    if stale_slugs:
        lines.append("")
        lines.append("## Stale pages")
        for s in stale_slugs:
            lines.append(f"- {s}")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Wiki lint (Pass A) + PII gate.",
    )
    parser.add_argument("--check-content", metavar="PATH",
                        help="Scan a candidate file for PII. Exit non-zero on match.")
    parser.add_argument("--wiki-root", default=".",
                        help="Path to the wiki root (contains wiki/, raw/). Default: cwd.")
    parser.add_argument("--migration", action="store_true",
                        help="Grandfather mode: new merge-Phase-2 error checks "
                             "report as warnings instead of errors.")
    args = parser.parse_args(argv)

    wiki_root = Path(args.wiki_root).resolve()

    if args.check_content:
        return check_content_cmd(Path(args.check_content), wiki_root)

    return full_lint(wiki_root, migration=args.migration)


def full_lint(wiki_root: Path, migration: bool = False) -> int:
    wiki_dir = wiki_root / "wiki"
    if not wiki_dir.exists():
        print(f"error: {wiki_dir} not found", file=sys.stderr)
        return 2

    # Load wiki-specific entity types from CLAUDE.md — falls back to builtins
    # if the file is absent or has no ## Entity types section.
    allowed_types = load_allowed_types(wiki_root)

    pages: dict[str, dict] = {}
    errors: list[str] = []
    new_errors: list[str] = []
    stale: list[str] = []
    summary_warnings: list[str] = []

    for md in wiki_dir.rglob("*.md"):
        rel = md.relative_to(wiki_dir)
        # Skip infrastructure: _drafts/, _archive/, _pii/, and _health.md itself.
        # The underscore-prefix check catches both subdirs AND top-level _health.md
        # because rel.parts[0] for wiki/_health.md is "_health.md".
        if rel.parts and rel.parts[0].startswith("_"):
            continue
        # Path-based slug to avoid collisions between wiki/index.md and wiki/log/index.md.
        # e.g. "log/index" for wiki/log/index.md, "shopify-competitor" for wiki/shopify-competitor.md.
        slug = str(rel.with_suffix("")).replace("\\", "/")
        text = md.read_text()
        fm, body = parse_frontmatter(text)
        open_q_count = len(
            [line for line in body.splitlines() if re.match(r"^\s*-\s\[\s\]", line)]
        )
        pages[slug] = {"fm": fm, "body": body, "path": str(rel), "open_questions": open_q_count}
        pages[slug]["trust"] = trust_counts(body)
        errors.extend(validate_frontmatter(fm, str(rel), allowed_types=allowed_types))
        new_errors.extend(check_author(fm, str(rel)))
        new_errors.extend(check_confidence_vs_sources(fm, str(rel)))
        # find_untagged_claims sees only the body, so its line numbers are
        # body-relative — shift them to file-relative by the number of lines
        # the frontmatter block occupies, or 0 if there's no frontmatter.
        fm_match = FRONTMATTER_RE.match(text)
        line_offset = text[:fm_match.start(2)].count("\n") if fm_match else 0
        claim_findings = find_untagged_claims(body, str(rel), fm.get("type", ""), line_offset=line_offset)
        new_errors.extend(claim_findings)
        pages[slug]["claim_findings"] = len(claim_findings)
        summary_warnings.extend(check_recommended_fields(fm, str(rel)))
        if is_stale(fm):
            stale.append(slug)

    orphans = find_orphans(pages)
    digest_name_warnings = check_digest_names(pages)

    # Upsert or remove human-visible trust lines on all non-synthesis pages.
    # The function itself decides whether to insert, update, or remove based on marker counts.
    for slug, p in pages.items():
        if p["fm"].get("type") == "synthesis":
            continue
        upsert_trust_line(wiki_dir / p["path"])

    has_entity_pages = any(
        p["fm"].get("type") not in ("synthesis",) for p in pages.values()
    )
    readability_warnings: list[str] = []
    if has_entity_pages:
        readability_warnings = check_bottom_line(pages) + check_overview(pages)

    strays = find_stray_files(wiki_root)
    dead_refs = find_dead_refs(pages)
    untagged_total = sum(p.get("claim_findings", 0) for p in pages.values())
    unacknowledged = find_unacknowledged_digests(pages)
    ext_ref_warnings = validate_external_refs(pages, wiki_root)
    evolution_warnings = check_evolution_triggers(pages, wiki_root)

    migration_deferred: list[str] = []
    if migration:
        migration_deferred = new_errors
        new_errors = []
    errors.extend(new_errors)

    # Write _health.md
    health_path = wiki_dir / "_health.md"
    health_path.write_text(render_health(
        pages, stale_count=len(stale), orphan_count=len(orphans),
        dead_refs=len(dead_refs), untagged_claims=untagged_total,
        strays=len(strays), stale_slugs=stale,
    ))

    # Generate and write §Agent Catalog into index.md
    catalog_text = generate_start_here(pages) + "\n\n" + generate_agent_catalog(pages)
    update_index_catalog(wiki_root, catalog_text)

    # Generate and write digests/catalog.md
    digests_dir = wiki_root / "wiki" / "digests"
    if digests_dir.exists():
        catalog_content = generate_digests_catalog(pages)
        (digests_dir / "catalog.md").write_text(catalog_content)

    # Generate wiki/questions/catalog.md if questions/ folder exists
    questions_dir = wiki_root / "wiki" / "questions"
    if questions_dir.exists():
        q_catalog = generate_questions_catalog(pages)
        (questions_dir / "catalog.md").write_text(q_catalog)

    if errors:
        print("SCHEMA ERRORS:", file=sys.stderr)
        for e in errors:
            print(f"  {e}", file=sys.stderr)
        return 2

    all_warnings = bool(
        stale or orphans or unacknowledged or ext_ref_warnings
        or summary_warnings or evolution_warnings or migration_deferred
        or digest_name_warnings or strays or dead_refs or readability_warnings
    )
    if stale:
        print(f"STALE ({len(stale)}): {', '.join(stale)}")
    if orphans:
        print(f"ORPHANS ({len(orphans)}): {', '.join(orphans)}")
    if digest_name_warnings:
        print(f"DIGEST NAMING ({len(digest_name_warnings)}):")
        for w in digest_name_warnings:
            print(f"  {w}")
    if strays:
        print(f"STRAY FILES ({len(strays)}): markdown outside wiki/ or raw/ — ingest or move; raw/ drops are always OK")
        for s in strays:
            print(f"  {s}")
    if dead_refs:
        print(f"DEAD REFS ({len(dead_refs)}):")
        for w in dead_refs:
            print(f"  {w}")
    if unacknowledged:
        print(f"UNACKNOWLEDGED DIGESTS ({len(unacknowledged)}): entity not updated after ingest")
        for entity_slug, digest_slug in unacknowledged:
            print(f"  {entity_slug} missing ← {digest_slug}")
    if ext_ref_warnings:
        print(f"EXTERNAL-REF WARNINGS ({len(ext_ref_warnings)}):")
        for w in ext_ref_warnings:
            print(f"  {w}")
    if summary_warnings:
        print(f"SUMMARY WARNINGS ({len(summary_warnings)}): add answer-preview summaries")
        for w in summary_warnings:
            print(f"  {w}")
    if readability_warnings:
        print(f"READABILITY ({len(readability_warnings)}):")
        for w in readability_warnings:
            print(f"  {w}")
    if evolution_warnings:
        print(f"EVOLUTION TRIGGERS ({len(evolution_warnings)}): wiki structure needs attention")
        for w in evolution_warnings:
            print(f"  {w}")
    if migration_deferred:
        print(f"MIGRATION-DEFERRED ({len(migration_deferred)}): errors grandfathered by --migration")
        for w in migration_deferred:
            print(f"  {w}")
    if all_warnings:
        return 1

    print(f"OK: {len(pages)} pages, no issues. Health written to {health_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
